Fail fast
Azure/rhel-jboss-templates pull request #92
Opened 2022-07-18 07:11 UTC by zhengchang907

## Main Change
Add fail fast scripts to check:
* UAMI is assigned as 'Contributor' or 'Owner' role of the deployment subscription
* There is enough computing resource for the deployment
* If users enabled Satellite server feature, validate the Satellite can be resolved based on provided FQDN

## Test
* Deploy the preview offer (with Domain mode and without Satellite)
* [Pipeline]()

2022-07-27 23:04 UTC, edburns commented on eap74-rhel8-payg-multivm/src/main/scripts/validate-parameters.sh
> +    # The function is used for scripts running within Azure Deployment Script
Why no

```
#!/usr/bin/env bash
set -Eeuo pipefail
```

2022-07-27 23:05 UTC, edburns approved these changes
See comments inline.

2022-07-27 23:06 UTC, edburns requested changes
See comments inline.

2022-07-28 06:32 UTC, zhengchang907 commented
Hi @edburns, I added the flag in the latest [commit](https://github.com/Azure/rhel-jboss-templates/pull/92/commits/a558195f50294c106c7cd1debeef87568c65bf0d)

2022-07-28 16:49 UTC, edburns approved these changes

2022-07-28 16:49 UTC, merged